#!/bin/sh

# Alias for directories
for num in {4..8}; do
  alias $num="cd ~/sem$num"
done

alias d="cd ~/Downloads"

# Alias for commands
alias r="ranger"
alias py="python3.11"
alias n="nemo . &"
alias l="ls"
alias z="zathura"
alias jl="jupyter-lab"
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias vim="nvim"
alias lg="lazygit"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

alias ssh='TERM=xterm-256color ssh'
alias ls='ls --color=auto'

alias config='/usr/bin/git --git-dir=/home/shikhar/.cfg/ --work-tree=/home/shikhar'
alias dg='/usr/local/bin/lazygit --git-dir=/home/shikhar/.cfg/ --work-tree=/home/shikhar'
