#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
nm-applet &
xautolock -detectsleep -time 10 -locker "betterlockscreen -l dim --off 10" &
dunst -config ~/.config/dunst/dunstrc &
picom --experimental-backends -b &
feh --bg-fill /home/shikhar/Pictures/Wallpapers/Fd0JbbnX0AMm5OE.jpeg &
$HOME/.config/polybar/launch.sh &


bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Set layout as tiled on all desktops
# for d in {1..10}
# do
#   bspc desktop `printf "^%d" ${d}` -l tiled
# done

bspc config border_width         2
bspc config window_gap          14

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a discord desktop='^9'
bspc rule -a Spotify desktop='^10'
bspc rule -a Blueberry.py follow=on desktop='^8' 
bspc rule -a Zathura state=tiled
bspc rule -a Alacritty state=tiled
bspc rule -a Yad --name=yad-calendar state=floating layer=above

# for_window [class="Spotify"] move to workspace $ws10
# assign [class="discord"] 9
# assign [class="Blueberry"] 8
# for_window [class="Yad" title="yad-calendar"] floating enable
#
#
